

spring:
   # Database configuration
   datasource:
      url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
      username: admin
      password: admin
      driverClassName: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
   # Enable web database access
   h2:
      console:
         enabled: true
         path: /h2-console
         
# Log configuration

# logs the SQL statements
logging.level:
      org.springframework.web: DEBUG
      com.memory.database: DEBUG
      # org.hibernate:
         # SQL: DEBUG
         # type.descriptor.sql.BasicBinder: TRACE

server.tomcat.accesslog:
   enabled: true
   pattern: common